
services:
  web1:
    build:
      context: ./django/
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    container_name: demo1
    volumes:
      - ./django/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles/
    env_file: 
      - ./.ini/dev.env
    environment:
      - CONTAINER_VERSION=1
    expose:
      - 8000
  
  web2:
    build:
      context: ./django/
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8080
    container_name: demo2
    volumes:
      - ./django/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles/
    env_file: 
      - ./.ini/dev.env
    environment:
      - CONTAINER_VERSION=2
    expose:
      - 8080

  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles

  dns:
    build:
      context: ./dns/
    container_name: dns
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zone/:/etc/bind/zone/
    command: named -c /etc/bind/named.conf -g -u named

volumes:
  static_files: